### PR TITLE
Repackage for EmbassyOS v0.3.0

### PR DESCRIPTION
**Pull request by elvece**
Makes the necessary changes to repackage this service for the upcoming release of EmbassyOS v0.3.0.

### CODE REVIEW

**Comment by viktorstrate** [comment]
Let me know if you need my help for anything :)
It would be nice to update Photoview as well to the latest release (v2.3.6 as of writing). A lot of great stuff has changed since.

**Comment by elvece** [comment]
Hi @viktorstrate 👋 for sure, thank you! I'm testing for backwards compatibility first, then planning to update to the latest version. New changes look awesome, stoked to get them on the Embassy.

**Comment by elvece** [comment]
Actually I do have a question, what would be a sane "health check" from your perspective? In this context, I mean either an api call, query, or other sanity check that ensures the application is running properly. More than one health check could exist. For example, if I have an application that is served on port 3000, I might `curl` that port to ensure its active and serving the intended response.

**Comment by viktorstrate** [comment]
The graphql query `SiteInfo` is publicly available and it reads the database for its response, I think that might be great for a healthcheck, as it will make sure the db connection is still working.

I checked some time ago and the container doesn't have curl installed, I think the best solution is to open an issue in the main repository and implement it into the docker image itself.

**Comment by elvece** [comment]
Great, thank you. Went ahead an opened up the PR [here](https://github.com/photoview/photoview/pull/552)

**Comment by elvece** [comment]
closing in favor of a new branch that indicates the package version to be released

**Pull request closed without merging**
